project:
  type: book
  output-dir: _book
  resources: 
    - _redirects

book:
  title: "Introduction to Modern Statistics (2e)"
  reader-mode: true
  page-footer:
    left: |
      This is IMS2e!
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/IMS2_front_cover.png
  favicon: images/openintro.png
  site-url: https://openintro-ims2.netlify.app/
  repo-url: https://github.com/openintrostat/ims/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - authors.qmd
    - preface.qmd
    
    - part: introduction-to-data.qmd
      chapters:
        - data-hello.qmd
        - data-design.qmd
        - data-applications.qmd
    
    - part: exploratory-data-analysis.qmd
      chapters:
        - explore-categorical.qmd
        - explore-numerical.qmd
        - explore-applications.qmd
        
    - part: regression-modeling.qmd
      chapters:
        - model-slr.qmd
        - model-mlr.qmd
        - model-logistic.qmd
        - model-applications.qmd
    
    - part: foundations-of-inference.qmd
      chapters:
        - foundations-randomization.qmd
        - foundations-bootstrapping.qmd
        - foundations-mathematical.qmd
        - foundations-errors.qmd
        - foundations-applications.qmd
    
    - part: statistical-inference.qmd
      chapters:
        - inference-one-prop.qmd
        - inference-two-props.qmd
        - inference-tables.qmd
        - inference-one-mean.qmd
        - inference-two-means.qmd
        - inference-paired-means.qmd
        - inference-many-means.qmd
        - inference-applications.qmd
    
    - part: inferential-modeling.qmd
      chapters:
        - inf-model-slr.qmd
        - inf-model-mlr.qmd
        - inf-model-logistic.qmd
        - inf-model-applications.qmd

  appendices:
    - exercise-solutions.qmd
    - references.qmd

bibliography: 
  - book.bib
  - eoce.bib
  - packages.bib

format:
  html:
    theme:
      light: [cosmo, scss/ims-style.scss]
      dark: [cosmo, scss/ims-style-dark.scss]
    code-link: true
    mainfont: Atkinson Hyperlegible
    monofont: Source Code Pro
    author-meta: "Mine Ã‡etinkaya-Rundel and Johanna Hardin"
    lightbox: 
      match: auto
      loop: false
    fig-dpi: 300
    fig-show: hold
    fig-align: center
  #pdf:
  #  include-in-header: latex/ims-style.tex
  #  include-after-body: latex/after-body.tex
  #  documentclass: book
  #  classoption: 
  #    - 10pt
  #    - openany
  #  pdf-engine: xelatex
  #  biblio-style: apalike
  #  keep-tex: true
  #  block-headings: false
  #  top-level-division: chapter
  #  fig-dpi: 300
  #  fig-show: hold
  #  fig-pos: H
  #  tbl-pos: H
  #  fig-align: center
  #  toc: true
  #  toc-depth: 2
    
editor: source

execute:
  freeze: auto
  echo: false
  cache: false
  warning: false 

knitr:
  opts_chunk: 
    dev: "ragg_png"
    fig-asp: 0.618  # 1 / phi
    fig-width: 8

comments:
  hypothesis: true
